boxes:
  - from: null
    to: null
    type: walk_action
    action:
      type: enter_battle
      against: random
      size: [1, 6]
      level: null
      reward_table: default
    if:
      new_tile: tallgrass
      chance: 0.025
