name: build-game
on:
  push:
    tags:
      - release-*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build game
        run: npm run build
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: game
          path: |
            build/arm64-*.zip
            build/x64-*.zip
